/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ManejaSerie;
import logica.Serie;

/**
 *
 * @author Gybram
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private final ManejaSerie manejaSerie;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        manejaSerie = new ManejaSerie();
        
        manejaSerie.agregarSerie("wilmer", 1996);
        this.rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEpisodios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tablaEpisodios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Serie", "Numero de Episodios", "Año lanzamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEpisodios.getTableHeader().setReorderingAllowed(false);
        tablaEpisodios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEpisodiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEpisodios);

        jButton1.setText("Agregar Serie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 47, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String nombreSerie = JOptionPane.showInputDialog(null, "Escriba nombre de la serie");
        String anioLanzamiento = JOptionPane.showInputDialog(null, "Año de lanzamiento");

        this.manejaSerie.agregarSerie(nombreSerie, Integer.parseInt(anioLanzamiento));

        this.rellenarTabla();

    }//GEN-LAST:event_jButton1ActionPerformed

    public void rellenarTabla() {
        // borra elementos existentes en la tabla
        DefaultTableModel tabla = (DefaultTableModel) tablaEpisodios.getModel();
        tabla.setRowCount(0);
        
        // rellena nuevamente la tabla con la el ArrayList de episodios
        DefaultTableModel model = (DefaultTableModel) tablaEpisodios.getModel();
        
        for (Serie serie : this.manejaSerie.getSeries()) {
            // TODO: averiguar que es object, y como se llena una JTable
            Object[] row = {serie.getNombre(), serie.getCantidadEpisodio(), serie.getAnio()};
            model.addRow(row);
        }
    }
    
    private void tablaEpisodiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEpisodiosMouseClicked
        // se obtiene el index de la fila
        int index = tablaEpisodios.getSelectedRow();
        
        // del ArrayList de series, se obtiene la serie a ver usando el index previamente obtenido
        Serie serie = this.manejaSerie.getSeries().get(index);
        
        // se crea una nueva vista de detalle de serie pasando como parametro la serie previamente obtenida
        VistaSerie vistaSerie = new VistaSerie(serie);
        vistaSerie.setVisible(true);
    }//GEN-LAST:event_tablaEpisodiosMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEpisodios;
    // End of variables declaration//GEN-END:variables
}
