/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ManejaSerie;
import logica.Serie;

/**
 *
 * @author Gybram
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private final ManejaSerie manejaSerie;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        manejaSerie = new ManejaSerie();
        
        manejaSerie.agregarSerie("gybramYelkin", 2002);
        this.rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeries = new javax.swing.JTable();
        btnAgregarSerie = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tablaSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Serie", "Numero de Episodios", "Año lanzamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSeries.getTableHeader().setReorderingAllowed(false);
        tablaSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSeriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSeries);

        btnAgregarSerie.setText("Agregar Serie");
        btnAgregarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSerieActionPerformed(evt);
            }
        });

        btnRecargar.setText("Recargar Tabla");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eg_stars_icon.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecargar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarSerie, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAgregarSerie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecargar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSerieActionPerformed
        // TODO add your handling code here:

        String nombreSerie = JOptionPane.showInputDialog(null, "Escriba nombre de la serie");
        String anioLanzamiento = JOptionPane.showInputDialog(null, "Año de lanzamiento");
        if(nombreSerie!=null & anioLanzamiento!=null){
            
            if(nombreSerie.isBlank()){
               JOptionPane.showMessageDialog(null, "no puede quedar en blanco", "Nombre", 3);
            }if(anioLanzamiento.isBlank()){
                JOptionPane.showMessageDialog(null, "no puede quedar en blanco", "Año", 3);
            }else{
                this.manejaSerie.agregarSerie(nombreSerie, Integer.parseInt(anioLanzamiento));
                this.rellenarTabla();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se añadio ninguna serie!", "Alert", 3);
 
        }  
    }//GEN-LAST:event_btnAgregarSerieActionPerformed

    public void rellenarTabla() {
        // borra elementos existentes en la tabla
        DefaultTableModel tabla = (DefaultTableModel) tablaSeries.getModel();
        tabla.setRowCount(0);
        
        // rellena nuevamente la tabla con la el ArrayList de episodios
        DefaultTableModel model = (DefaultTableModel) tablaSeries.getModel();
        
        for (Serie serie : this.manejaSerie.getSeries()) {
            // TODO: averiguar que es object, y como se llena una JTable
            Object[] row = {serie.getNombre(), serie.getCantidadEpisodio(), serie.getAnio()};
            model.addRow(row);
        }
    }
    
    private void tablaSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSeriesMouseClicked
        // se obtiene el index de la fila
        int index = tablaSeries.getSelectedRow();
        
        // del ArrayList de series, se obtiene la serie a ver usando el index previamente obtenido
        Serie serie = this.manejaSerie.getSeries().get(index);
        
        // se crea una nueva vista de detalle de serie pasando como parametro la serie previamente obtenida
        new VistaSerie(serie).setVisible(true);
    }//GEN-LAST:event_tablaSeriesMouseClicked

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        rellenarTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSerie;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSeries;
    // End of variables declaration//GEN-END:variables
}
